/**
 * Linhas de exemplo (mapas achatados, formato de linha de CSV).
 *
 * Fonte única: o `template.csv` do backend e o botão "Exemplo PF/PJ" do cadastro
 * individual leem daqui. Antes viviam só em `apps/api/src/template.ts`; ficar em
 * `shared` evita que a tela e o template divirjam.
 *
 * São dados FICTÍCIOS (documentos genéricos de teste) — nunca tomadores reais.
 */

/** Exemplo PF — espelha o payload validado em HML. */
export const EXEMPLO_PF: Record<string, string> = {
  dsNome: "Geraldo Luiz Bruno Aragão",
  nrCpfCnpj: "15032465070",
  sgEstado: "PA",
  dtAbert: "20001205",
  dtValcad: "20260307",
  cdSituac: "1",
  dsSituac: "ATIVO",
  nrCep: "67110570",
  dsEnd: "Passagem São José de Ribamar",
  nrEnd: "681",
  dsBairro: "Guanabara",
  dsCidade: "Ananindeua",
  nrDDD: "91",
  nrTel: "25969156",
  nrDDDCel: "91",
  nrCel: "994453733",
  dsEmail: "geraldo-aragao98@br.festo.com",
  cdPess: "1",
  cdAtvCl: "0",
  cdAutscr: "S",
  cdGrupo: "1",
  cdPais: "1",
  "bensImoveis[0].idAcao": "IN",
  "bensImoveis[0].cdPais": "1",
  "bensImoveis[0].nmImovel": "Casa",
  "bensImoveis[0].tpImovel": "1",
  "bensImoveis[0].nmEnd": "Passagem São José de Ribamar",
  "bensImoveis[0].nrEnd": "681",
  "bensImoveis[0].nmBairro": "Guanabara",
  "bensImoveis[0].nmCidade": "Ananindeua",
  "bensImoveis[0].nrCep": "67110570",
  "bensImoveis[0].sgEstado": "PA",
  "dadosBancarios[0].idAcao": "IN",
  "dadosBancarios[0].nrBanco": "1",
  "dadosBancarios[0].nrAgencia": "1584",
  "dadosBancarios[0].nrConta": "144460",
  "dadosBancarios[0].dvConta": "7",
  "dadosBancarios[0].idPrincipal": "S",
  "dadosBancarios[0].dtAbert": "19900101",
  "dadosPf.dtNasc": "19800120",
  "dadosPf.tpSexo": "M",
  "dadosPf.cdProf": "2",
  "dadosPf.tpDoc": "1",
  "dadosPf.nrDoc": "236451467",
  "dadosPf.sgEmissor": "SSP",
  "dadosPf.dtEmissao": "19990101",
  "dadosPf.sgEstadoNat": "MG",
  "dadosPf.cdEstCivil": "1",
  "dadosPf.idUniao": "2",
  "dadosPf.nomeMae": "Marcelo Danilo Aragão",
  "dadosPf.nomePai": "Elza Isadora",
  "dadosPf.naturalidade": "1200401",
  "dadosPf.nomeCidadeNaturalidade": "Belo Horizonte",
  "dadosPf.nacionalidade": "1",
  "dadosPf.idGrinst": "4",
  "dadosPf.nrDepend": "0",
  "dadosPf.idLe6515": "N",
  "dadosPf.cdPais": "1",
  "dadosProfissionais.cdProf": "2",
  "dadosProfissionais.dsCargo": "MEDICA",
  "dadosProfissionais.dtAdmis": "20000307",
  "dadosProfissionais.vlRendaBruta": "17992.40",
  "dadosProfissionais.vlRendaLiquida": "15000.00",
  "dadosProfissionais.cdPorte": "8",
  "dadosProfissionais.cdLoctb": "1",
  "dadosProfissionais.cdPais": "1",
  "dadosProfissionais.nrCep": "38412851",
  "dadosProfissionais.nmEnd": "Rua Mogno",
  "dadosProfissionais.nrEnd": "450",
  "dadosProfissionais.nmBairro": "Arroio da Manteiga",
  "dadosProfissionais.nmCidade": "São Leopoldo",
  "dadosProfissionais.sgEstado": "RS",
  "refPessoais[0].nome": "MARIA DAS DORES",
  "refPessoais[0].nrDDDTel": "31",
  "refPessoais[0].nrTel": "34567890",
};

/** Exemplo PJ (usa dadosPj; nunca dadosPf — o schema rejeita os dois juntos). */
export const EXEMPLO_PJ: Record<string, string> = {
  dsNome: "Egalite Recursos Humanos Especiais LTDA",
  nrCpfCnpj: "10766388000190",
  sgEstado: "RS",
  dtAbert: "20090416",
  dtValcad: "20260307",
  cdSituac: "1",
  dsSituac: "ATIVO",
  nrCep: "90470282",
  dsEnd: "Avenida Carlos Gomes",
  nrEnd: "1672",
  dsBairro: "Auxiliadora",
  dsCidade: "Porto Alegre",
  nrDDD: "51",
  nrTel: "3427690775",
  nrDDDCel: "51",
  nrCel: "984103717",
  dsEmail: "egalite@gmail.com",
  cdPess: "23",
  cdAtvCl: "0",
  cdAutscr: "S",
  cdGrupo: "1",
  cdPais: "1",
  "dadosBancarios[0].idAcao": "IN",
  "dadosBancarios[0].nrBanco": "1",
  "dadosBancarios[0].nrAgencia": "1584",
  "dadosBancarios[0].nrConta": "144460",
  "dadosBancarios[0].dvConta": "7",
  "dadosBancarios[0].idPrincipal": "S",
  "dadosBancarios[0].dtAbert": "19900101",
  "dadosPj.amFatMes": "1000000",
  "dadosPj.cdCapital": "N",
  "dadosPj.cdSetor": "1",
  "dadosPj.cdTribute": "2",
  "dadosPj.dtAberturaEmpresa": "20090416",
  "dadosPj.idConsti": "1",
  "dadosPj.idContAcio": "1",
  "dadosPj.nomeFantasia": "Egalite RH",
  "dadosPj.qtFuncio": "0",
};
